[build-system]
requires = [
    "setuptools>=46",
    "wheel",
    "oldest-supported-numpy",
    "setuptools_scm>=8",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "redmapper/_version.py"
